Revert "adb: add transport benchmark."
This reverts commit 7bb5fb8128fe7827a422f072266e8a2c9f3bdb9b.

Reason for revert: Breaks aosp-master renderscript and sdk_mac:
  error: system/core/adb/Android.bp:199:19: unrecognized property "host_supported"

Change-Id: Ifd75921dcdf5dce57f98833a913540914984b293